# Generated by Django 3.0.7 on 2020-07-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe', '0003_auto_20200710_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='attempt_num',
            field=models.IntegerField(default=1, verbose_name='Submission Attempt Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.IntegerField(verbose_name='Canvas Submission ID'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('submission_id', 'attempt_num'), name='unique_canvas_submission'),
        ),
    ]
