# Generated by Django 3.0.7 on 2020-07-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe', '0004_auto_20200716_1322'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submission',
            name='unique_canvas_submission',
        ),
        migrations.AlterField(
            model_name='submission',
            name='attempt_num',
            field=models.IntegerField(null=True, verbose_name='Submission Attempt Number'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('submission_id', 'graded_timestamp'), name='unique_canvas_submission'),
        ),
    ]
